services:
  - type: web
    name: fastapi-inventory-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        value: http://localhost:5173,http://127.0.0.1:5173
